### PR TITLE
add JSONList option to logger

### PR DESCRIPTION
**Pull request by nazarewk**
Allows `JSONList` for JSON formatter allows retaining multiple values for same key just like standard formatter does.

### CODE REVIEW

**Comment by nazarewk** [comment]
It can help with preserving multi-level context in JSON formatted logs, for example (which works fine with non-json logger):
1. `logger.With("action", "read")`
1. `logger.With("action", "create")`
  1. `logger.With("action", "read")`
instead of (because JSON formatter overrides values):
1. `logger.With("action_read", true)`
1. `logger.With("action_create", true)`
  1. `logger.With("action_read", true)`

**Comment by jefferai** [comment]
I don't understand the difference in the examples above, but Isn't this just a bug in the non-JSON logger? It feels like if you are specifically setting a key it should *always* overwrite/replace existing values.

**Comment by nazarewk** [comment]
@jefferai 
Looks like you are right.

Would it be acceptable if I created some kind of value wrapper indicating that the key should be a list instead of overriding previous values? I'd love to see merge-style logging keys

**Comment by jefferai** [comment]
I think that's something that should be done by the user instead of as a special feature of the logging library. @evanphx what do you think?

**Comment by evanphx** [comment]
GIven #22, I think this can be closed.

**Pull request closed without merging**
