### PR TITLE
Add color support to nonJSON loggers

### PR DESCRIPTION
**Pull request by RobbieMcKinstry**
Doesn't have a test right now… if you think this change warrants testing I'll gladly add something :)
I just wanted to get some eyes on this before I go any farther :)

Thank you!

### CODE REVIEW

**Comment by jefferai** [comment]
Coloring is super tricky, it's different across terminals, platforms, etc. I don't think using the codes here directly is portable...I can point you to some libraries we use in vault that handles the cross platform stuff.

**Comment by RobbieMcKinstry** [comment]
Hi @jefferai! Thanks, I'd appreciate it. I ported this directly from `mitchellh/colorstring`, but as you noted it's not portable.

**Comment by jefferai** [comment]
We're using https://github.com/fatih/color and  https://github.com/mattn/go-colorable

The latter is the main event, providing colorable terminals across platforms; the former is for a single var we use (NoColor; see https://godoc.org/github.com/fatih/color#pkg-variables)

See https://github.com/hashicorp/vault/blob/master/command/main.go for more info.

**Comment by evanphx** [comment]
@RobbieMcKinstry Feel free to open a new PR that uses either of the 2 packages @jefferai mentions.

**Pull request closed without merging**
