### PR TITLE
Update the logger so it logs to stdout and stderr

### PR DESCRIPTION
**Pull request by svanharmelen**
Previously all log messages would (by default) be written to stderr, but after this update it will only log error messages to stderr and all other messages to stdout.

https://app.asana.com/0/974609005970545/897114012136425

For reviewing it's probably good to review this PR per commit (2 in total). The first commit only updates some comments to silence my linters and does a very light refactoring of the internal logger (without any functional changes or changes to the public API of course).

The second PR adds some new logic to facilitate splitting the logs between stdout and stderr.

### CODE REVIEW

**Comment by jefferai** [comment]
@svanharmelen Please put the refactoring/linting and the behavior changes into separate PRs.

Additionally, I'm a strong "no" on this as it changes default behavior in an incompatible way. You can already easily chose where *all* logs go, so this can already be achieved via a custom io.Writer implementation. But if we want this functionality in this package, we should provide for a formalized way to specify the writer per level.

**Comment by evanphx** [comment]
Yeah, I'm going to veto this as well. The default `log` package sends everything to `stderr`, which was the reason that `hclog` did as well. The usage of `hclog` is well established enough on it's own that we can't change this by default, that's without considering what the users expectation is as it relates to use `hclog` instead of `log`.

If this is functionality you want, exposing it via a config option would be fine.

**Comment by svanharmelen** [comment]
> Please put the refactoring/linting and the behavior changes into separate PRs.

Will do.

> I'm a strong "no" on this as it changes default behavior in an incompatible way.

So would you be open to adding logic that makes this behavior optional/configurable?

> so this can already be achieved via a custom io.Writer implementation

True, but that would be a pretty poor way to solve this as that would mean you would have to scan each log message in the writer where you don't have access to the log levels that are used inside the  logger.

**Comment by svanharmelen** [comment]
I did already expect this feedback by the way :wink: Just thought opening the PR anyway would probably be the best way to discuss options.

**Comment by evanphx** [comment]
Exposing the behavior by allowing the Writer to conform to a new interface like: ```
type SegregatedWriter {
   ErrorWrite([]byte) (int, error)
  Write([]byte) (int, error)
}
```

Might be a good path to take here.

**Comment by evanphx** [comment]
Or perhaps:

```golang
type LevelWriter interface {
   LevelWrite(level Level, b[]byte) (int, error)
}
```

**Comment by svanharmelen** [comment]
> If this is functionality you want, exposing it via a config option would be fine.

I'm not sure if I want this, but I think it solves (part of) the Asana I linked to.

```go
type LevelWriter interface {
   LevelWrite(level Level, b[]byte) (int, error)
}
```

Yeah that seems like a good interface. Let's see if I can update the PR using that approach 👍

**Comment by svanharmelen** [comment]
I'll close this one for now.

**Comment by jefferai** [comment]
Yep, LevelWriter looks good.

**Pull request closed without merging**
